### ISSUE TITLE
Helper functions for DoubletFinder

### ISSUE THREAD

**Issue by ccruizm** [mckellardw/scMuscle#1]
Hello @mckellardw!

Thanks for making your code available. Great work! I was looking at how to automate the `DoubletFinder` pipeline and I saw your nice script. However, I could not find the helper functions for this part of the pipeline in your `helper_functions_v1.R` file. Could you share them, please?

Thanks in advance!

**Comment by mckellardw** [comment]
Sorry about that! `helper_functions_v1.R` is updated to include those two functions. They include a function to estimate the doublet rate in a count matrix (specifically from 10x chromium data), and two of the DoubletFinder functions with a little bit extra functionality (mostly just the ability to specify the column name in the Seurat object where doublet status and pANN output are stored. This makes merging/integrating many datasets much cleaner as each of them will have slightly different parameterization, which by default will show up in those metadata col names).

**Comment by ccruizm** [comment]
Thank you very much for updating the file! Will give it a try.
