### ISSUE TITLE
Impossible to load the data on the web app

### ISSUE THREAD

**Issue by CroixJeremy2** [mckellardw/scMuscle#10]
Hello,
It seems that I can't navigate through your data on the web app. I get this error message on every tab:
<img width="1985" alt="Screenshot 2023-06-20 at 10 52 44" src="https://github.com/mckellardw/scMuscle/assets/27291483/c5747023-024d-4944-a668-81358270d852">
When I go to http://scmuscle.bme.cornell.edu/ , my web browser is loading the data as I have to wait (loading icon):
<img width="1951" alt="Screenshot 2023-06-20 at 10 57 00" src="https://github.com/mckellardw/scMuscle/assets/27291483/490474ab-c68a-4329-a5c9-fe5901fa7d08">
At some point, it stops, and it says "Check your logs", but I don't know where to look at them. Do you know how to solve the problem? I am on an iMac (Retina 4K, 21.5-inch, 2017), CPU: 3,4 GHz Quad-Core Intel Core i5. Memory: 16 GB 2400 MHz DDR4.
At some point I tried to download the whole dataset and to read it in R directly, but my computer does not have enough memory to read scMuscle_mm10_slim_v1-1.RData apparently... So I would like, at least, to use the web app.
Thanks in advance for your response, and thanks again for having generated such a huge interesting integrated scRNA seq object !
Best regards,

**Comment by mckellardw** [comment]
Thanks for letting us know! This has been a recurring problem, and we are actively working on transitioning to a better platform for hosting the dataset (stay tuned!).

In the meantime, I rebooted the server so you should be able to use it as before.
