### ISSUE TITLE
Loading spatial data without h5 file

### ISSUE THREAD

**Issue by dwmurray8** [mckellardw/scMuscle#2]
Hi all,

It is unclear to me how Visium data can be loaded into R in the absence of an h5 file. Previously, I have managed to load Visium data using the Load10X_Spatial function with very little problem. However, when working with data that does not provide this file, it seems much more difficult to do. I am following this code provided by mckellardw: R_scripts/visium_github_v1.R

I am unsure of which of his paths lead to which files. I have access to filtered_feature_matrix (barcodes.tsv, features.tsv, matrix.mtx), json, tiff, and csv files. 

Any guidance that can be provide here is much appreciated.

**Comment by mckellardw** [comment]
The files provided in our GEO submission are outputs from spaceranger, the alignment workflow from 10x Genomics designed specifically for Visium data. Details on that workflow can be found [here](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/count). The files within "filtered_feature_matrix" contain the count matrices for each sample. The .tiff files are the H&E images generated during the Visium workflow. The .csv files contain all the metadata for each sample/spot.  The .json file is needed for the spaceranger workflow to manually pick spots which are under the tissue sections.

To make things easier for you, I added a new directory (`visium_data`) which has the .h5 files in it. Let me know if you have any further issues!
