### ISSUE TITLE
adding inferred cell types 

### ISSUE THREAD

**Issue by skim245** [mckellardw/scMuscle#6]
I have two additional questions related to Fig.4e 

are there any easy ways to add cell type predictions to original seurat object? 
and how can we overlay the inferred cell type content to Visium spot like Fig.4e? 

Thank you again :)

**Comment by mckellardw** [comment]
When you say "original seurat object", do you mean the visium objects or the single-cell objects? In my code, I add the BayesPrism outputs as a separate assay, but you could also add them as columns in the meta.data.

I added the spatial locations of each spot as a separate reduction in the seurat objects (called "space" in my R scripts), then visualized everything with the `DimPlot()` function from Seurat. This can distort the images if you aren't careful though, so another option would be to follow visualization suggestions from the Seurat team which you can find in [this vignette](https://satijalab.org/seurat/articles/spatial_vignette.html).

**Comment by skim245** [comment]
@mckellardw  thank you for the prompt response! 
I want to add the BayesPrism outputs as columns in the VIsium object meta.data. 
I will try both of your suggestions and see how it goes! 
Thank you:)
