### ISSUE TITLE
Seurat Object loading as 'character' from RData file

### ISSUE THREAD

**Issue by LaviCor** [mckellardw/scMuscle#8]
Hello all,

I recently downloaded the "scMuscle_mm10_slim_v1-1.RData" from the dryad data repository.

the file type is listed to be RData, so i tried to load it into R using the 'load' function.
however when trying to use any of seurat functions, it says it cannot do so as the object is of "character" type.
using "typeof" returned that the type of the object was indeed "character".

However, in the data window, the object was listed to be "Large Seurat".
In addition, when inspecting the object structure, everything looked fine, save for the type of the first row (the object as a whole?), which was listed to be a S4(Seurat::Seurat), instead of the S4(SeuratObject::Seurat) which is shown for regular working data I have.
![image](https://user-images.githubusercontent.com/101585799/181300922-62ac9c47-043e-434a-a11a-ae9324e6d598.png)
vs
![image](https://user-images.githubusercontent.com/101585799/181300950-680a85eb-8e70-429a-8f3e-2d626248e69a.png)

Also, when downloading the file, it was listed as just "file" type (not RData), and the file name had no extension.

I have no idea how to solve this issue, so any help on how to properly load or convert the data to a working seurat object would be much appreciated.

**Comment by mckellardw** [comment]
I'm happy to help! Based on the preview you are showing, it looks like you have successfully downloaded the Seurat object which just contains the myogenic cells (Fig 2 & Fig 3 in the paper). It also looks like you have successfully loaded it into R. The differences you see in the classes between the 2 objects are because they were built with different versions of Seurat (v3 for our scMuscle data, v4 for your data). Could you share any error messages that you get? Otherwise I don't think you have any issue...

**Comment by LaviCor** [comment]
Thanks for the reply!
![image](https://user-images.githubusercontent.com/101585799/181589544-2577ceb2-71f4-44ac-96fe-4e23f5368e0e.png)
This is what happens when I try to run some basic Seurat stuff.
For most things I tried to run, it says it cannot do so as the object is a "character" (like viewing factor levels of some meta.data slots)

How would you load an object like this into R? maybe this is were I get it wrong?

**Comment by mckellardw** [comment]
Looks like there isn't anything wrong with the Seurat objects. Please check the reductions which are saved in the Seurat object by running `Reductions(SCgiant)`. The myogenic cell data does not have a UMAP embedding saved, as we opted to instead use PHATE to analyze myogenesis. 

If you would like to look at the full dataset which includes all cell types, you can download it from the same Dryad repository. Thanks!
